### ISSUE TITLE
Problem with "editthread"

### ISSUE THREAD

**Issue by AxelBriche** [Contex/XenAPI#41]
With "editthread", I can update the **title** but not **message** and if I edit the message and not the title, I have an error message: http://i.imgur.com/73ZvnnI.png. You have forget **message** inside this action in the API I think.

And after update, the date of the first message of the thread is not updated:  "5 minutes ago".

I have not try with editmessage.

**Comment by Contex** [comment]
It works with **editpost** as the first message/post in a thread is a post object and not a thread.
