### ISSUE TITLE
Request - Multiple actions in one request

### ISSUE THREAD

**Issue by robputer** [Contex/XenAPI#48]
Would love the ability to chain multiple actions into one HTTP API call.

Example: I want to get the user's avatar, and any alerts.  More efficient to put these two into one api call.

Thanks!

**Comment by Contex** [comment]
Sadly, I don't see this being implemented anytime soon as it would require a lot of rework. A more proper way would be to create some kind of customization/extension framework that allows creating your own commands and such.

That won't happen until 2.0, if I ever get there.
