### ISSUE TITLE
Add API call to get latest posts

### ISSUE THREAD

**Issue by Rmarmorstein** [Contex/XenAPI#52]
It would be very useful to have an API call to get the latest threads, posts, etc. I did not see this on the wiki page for the list of actions.

Either way, this is a great add-on and I certainly appreciate the work you've put into it!

**Comment by Contex** [comment]
You can use the order_by parameter with getPosts, getThreads and getProfilePosts like so:
```
api.php?hash=x&action=getPosts&order_by=post_date&order=desc
```

The documentation is unfinished but the code is implemented.
Check the source for what fields that you can order by, for example [getPosts](https://github.com/Contex/XenAPI/blob/master/net/xenapi/XenAPI/api.php#L2177) can be ordered by:
```
'post_id', 'thread_id', 'user_id', 'username', 'post_date', 'attach_count', 'likes' and 'node_id'
```
