### ISSUE TITLE
editUser() method doesnt return json - instead returns php warnings

### ISSUE THREAD

**Issue by z1haze** [Contex/XenAPI#53]
when attempting to run editUser() this is what im seeing returned

Warning: unserialize() expects parameter 1 to be string, array given in /www/site.com/public/api.php on line 4066

Warning: array_diff_assoc(): Argument #1 is not an array in /www/site.com/public/api.php on line 4066

Warning: Invalid argument supplied for foreach() in /www/site.com/public/api.php on line 4071

Warning: Cannot modify header information - headers already sent by (output started at /www/site.com/public/api.php:4066) in /www/site.com/public/api.php on line 3221
{"username":"test","advapps":null}

**Comment by z1haze** [comment]
I tracked it down something in your check here. I wasnt using any custom fields

if (!empty($diff_array['custom_fields'])) {
            // Check the difference in the custom fields.
            $custom_fields_diff_array = array_diff_assoc(unserialize($user->data['custom_fields']), unserialize($diff_array['custom_fields']));

            unset($diff_array['custom_fields']);

            // Loop through the differences and add them to the diff array.
            foreach ($custom_fields_diff_array as $custom_fields_diff_key => $custom_fields_diff_value) {
                $diff_array['custom_fields'][$custom_fields_diff_key] = $custom_fields_diff_value;
            }
        }

for now I just commented that block and its working

**Comment by Contex** [comment]
Thanks for saving me the time! I will have a look for a fix whenever I get some free time.

**Comment by z1haze** [comment]
have you solved this yet? I was going to close this.
