### ISSUE TITLE
createThread

### ISSUE THREAD

**Issue by nohopes** [Contex/XenAPI#55]
Hey Guy´s
api.php?performance&hash=API_KEY&action=createThread&grab_as=USER&node_id=ID&title=Test2&message=aishfdosadfhoisd

This will work fine, but the Threads are moderated. .. can any help me ?

{"user_id":x,"username":"x","title":"Test2","prefix_id":0,"node_id":x,"discussion_state":"moderated","post_date":1445360368,...............

**Comment by Contex** [comment]
'discussion_state' is inherited from the default post insert message state of the forum you are posting to ( [this line to be more specific](https://github.com/Contex/XenAPI/blob/master/net/xenapi/XenAPI/api.php#L3597)).

Could you try posting to another node_id instead?

**Comment by nohopes** [comment]
How can i fix it?

**Comment by Contex** [comment]
Fixed in bc7de1820a9f30a105caf2235bf70c3b6131f34a
