### ISSUE TITLE
get userid by ip

### ISSUE THREAD

**Issue by Codez1337** [Contex/XenAPI#58]
is there anyway to grb the users ip by putting their userid?

**Comment by Contex** [comment]
Added this feature for the next version

`api.php?hash=HASH&action=getusers&value=188.114.111.30`

> [{"user_id":14,"username":"AliConnon","log_date":1440011635},{"user_id":12,"username":"DarrylBaumli","log_date":1440650777},{"user_id":10,"username":"DougLedermann","log_date":1440648636},{"user_id":9,"username":"StephanMccalpin","log_date":1440650283}]

**Comment by Codez1337** [comment]
thats a bit backwards but i guess it will work.
