### ISSUE TITLE
How you get user hash?

### ISSUE THREAD

**Issue by matthew4444** [Contex/XenAPI#63]
im a bit new to xenforo,so how u get user hash?

**Comment by Contex** [comment]
`api.php?action=authenticate&username=Contex&password=123456`

Returns:
`{"hash":"JDJhJDEwJGZOQU1ZQkdya1ZHMEVjck9YOXJZZXUvL2VGMVpyTzJDSTFJNUlGVWFBVzN6NS95OUJLMnVP"}`

**Comment by matthew4444** [comment]
kk
