### ISSUE TITLE
Query by IP

### ISSUE THREAD

**Issue by ghost** [Contex/XenAPI#70]
In order to query the API we use user/pass or API key. Is there any possibility to have an _optional_ item to also query by API key plus IP address?

**Comment by ghost** [comment]
... so only that/those IP address(es) along with API key get valid data returned.

**Comment by ghost** [comment]
.. actually thinking about this again. Also would it be possible to also query by user/pass plus IP address(es) too?

**Comment by bato3** [comment]
My guess is that you want to protect, to work with the IP specific API key.

If so, add the line:
`if ($_SERVER [ "REMOTE_ADDR"] == '192.168.0.1')`
before
`$restAPI = new RestAPI('API_KEY_FOR_192.168.0.1');`

**Comment by ghost** [comment]
Hi Bato,
  I don't do PHP but that has resolved my potential MIM attack on my none-SSL site. Now using, if ($_SERVER [ "REMOTE_ADDR"] == '192.168.0.1' || $_SERVER [ "REMOTE_ADDR"] == '192.168.0.2') for multiple allowed IP's.

Thanks :+1:
