### ISSUE TITLE
is_staff

### ISSUE THREAD

**Issue by Kaan2106** [Contex/XenAPI#75]
Is there a way to get the "is_staff" status [0 OR 1] (in table xf_user) ?

waves'

**Comment by segg21** [comment]
I'm thinking about starting up another project similar as this with better features, optimizations, and faster responses.

Besides, this is really outdated. You might as well grab the databases yourself to check for staff.

**Comment by Kaan2106** [comment]
I'm currently working with XenForo 1.4.10.
No thats no problem to grab the needed informations from database itself, but I doen't want to put "so many" MySQL queries into the plugins for my server (minecraft).
That's why I decided to use XenApi - well it's working right now, but there are so many functions missing like you said.

I looking forward to you, LegitSoulja.

**Comment by segg21** [comment]
@Kaan2106

Why are you putting sql with your plugins when it's best to use server side PHP and direct requests from Java and your web service

**Comment by Kaan2106** [comment]
Because our plugins working with MYSQL already like add / remove from other table (for example /promote <User> <Rank> adds in table "team" 'id' (by autoincrement), 'user-id' and 'Moderator'.
Then the plugin promotes the user to the rank 'Moderator' but aren't set him / her to the status "is_staff". Also the user get's the rank but isn't shown on the "members" (team) page because is_staff is 0.
I though, using the API would be awesomer and easier (and much more efficiency) as much many mysql-queries.

(sorry for my bad english, just now back from work q_q)

**Comment by segg21** [comment]
@Kaan2106 Let me look more into the xenapi and see if you can get staff. Im pretty sure you can. You can get admin i know for a fact.

Have you looked at any of the output from any of the requests?

**Comment by segg21** [comment]
@Kaan2106 Yes, by the looks you can.

> ?**action**=getUser&**value**=[name or id]&**hash**=[api key, or value hash] 

Just send a POST request http call from java to your forum /api.php, and get the result,
parse the json and get **is_staff**

**Comment by cloudburstwan** [comment]
If you're still working on this @Kaan2106
Pocketmine expresses a post function at pocketmine/utils/Utils->postURL();
we'll say pocketmine/utils/Utils is Utils.
you would use the following code to get user data
$player is an IPlayer.
$this->APIKEY is a private variable containing the api key
$this->APIENDPOINT is a public variable containing the url for the api without api.php
```
$data = Utils::postURL($this->APIENDPOINT."api.php",
           array(
               'action' => "getUser",
               'value' => $player->getName(),
               'hash' => $this->APIKEY,
           )
);
```

Using that you can then use $data["is_staff"] once you are certain that the api didn't throw an error.

**Comment by Kaan2106** [comment]
@LegoDevStudio  I don't work on this anymore. I found a workaround.  
Thanks for your reply anyways. 
I hope this should help someone in the future.
