### ISSUE TITLE
Optimized

### ISSUE THREAD

**Issue by segg21** [Contex/XenAPI#76]
I was thinking about re-writing something as similar as this but better, but I've done some tests and see that the slow performance is caused by loading times. There's nothing wrong with this, and is better than anything I've seen so far with mostly all the forum functionalities. API.php is pretty heavy. 

I've reduced the load time by calling those classes that's needed. Mainly I took all the classes out and moved them all into /api. I'm satisfied now that the site I'm using xenapi loads way much more faster.

Now, since I organized things it's better to work with if I need to extend xenapi further. Anyways thanks for this. You saved me soo much time(If I had to develop something as similar as this).

**Comment by bato3** [comment]
@LegitSoulja
Can you send your changes to the git? Gladly I would use an optimized version.

**Comment by segg21** [comment]
@bato3 what do you mean?
